config/routes.rb
Rails.application.routes.draw do
  resources :residents

  root 'residents#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  validates :zipcode, presence: true,
                      length: { maximum: 255 },
                      numericality: { only_integer: true }
  validates :street, presence: true,
                     length: { maximum: 255 }
  validates :neighboorhood, presence: true,
                            length: { maximum: 255 }
  validates :city, presence: true,
                   length: { maximum: 255 }
  validates :state, presence: true,
                    length: { is: 2 }
  validates :ibge_code, allow_blank: true,
                        numericality: true,
                        length: { maximum: 255 }
  validates :complement, allow_blank: true,
                         length: { maximum: 255 }

  before_validation :cleasing

  def cleasing
    self.zipcode = zipcode.to_s.gsub(/\D/, '')
    self.ibge_code = zipcode.to_s.gsub(/\D/, '')
    self.state = state.to_s.downcase
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include Utils::Filter

  self.abstract_class = true
end

app/models/concerns/utils/filter.rb
module Utils::Filter
  extend ActiveSupport::Concern

  included do

    scope :search, -> (params, value) do
      unless value.blank?
        query = []
        params.each do |k|
          query.push(query_builder(k,value))
        end
        return self.where(query.to_sentence(words_connector: 'or ', two_words_connector: 'or ', last_word_connector: 'or '))
      end
    end

  end

  module ClassMethods
    def query_builder(k,value)
      if ActiveRecord::Base.connection.adapter_name == "PostgreSQL"
        return "unaccent(#{k.to_s}::text) ilike unaccent('%#{value}%')"
      else
        return "#{k.to_s} like '%#{value}%'"
      end
    end
  end
  
end

app/models/resident.rb
class Resident < ApplicationRecord
  
  has_one_attached :photo
  
  enum status: { inactive: 0, active: 1 }
  has_enumeration_for :status, with: ResidentEnum::Statuses, create_helpers: true
  has_many :addresses, as: :addressable
  validates :full_name, presence: true, length: { maximum: 255 }
  validates :document, presence: true, cpf: true
  validates :health_card_document, presence: true
  validates :email, presence: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },
                    length: { maximum: 255 }
  validates :birthdate, presence: true
  validates :phone, presence: true
  validates :photo, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'],
                                            size_range: 1..(5.megabytes) }

  validate :birthdate_between_zero_and_125_years_ago
  accepts_nested_attributes_for :addresses
  
  before_validation :cleasing

  private

  def birthdate_between_zero_and_125_years_ago
    return if birthdate.blank?

    errors.add(:birthdate, :invalid) if birthdate > Date.today || birthdate < 125.years.ago
  end

  def cleasing
    self.health_card_document = health_card_document.to_s.gsub(/\D/, '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController

  def index
    @residents = Resident
                .all
                .search(search_params, params[:search])
  end

  def edit
    @resident = Resident.find(params[:id])
  end

  def new
    @resident = Resident.new
    @resident.addresses.build
  end

  def create
    @resident, @addresses =
      Residents::CreatorService.call(valid_params: valid_params)
    if @resident.save
      SmsService.new.send_sms(@resident)
      redirect_to residents_path
    else
      flash[:errors] = "Erro ao Criar Municipe"
    end  
  end

  private
  
  def valid_params
    addresses_attributes =
        %i[id zipcode street complement neighboorhood city state ibge_code]

    params.require(:resident)
          .permit(:full_name, :document, :health_card_document, :email,
                  :phone, :birthdate, :status, :photo, addresses_attributes: addresses_attributes)
  end

  def search_params
    ["residents.full_name", "residents.email", "residents.status", "residents.phone",]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
  def format_brazilian_health_card_number(value)
    "#{value[0,3]} #{value[3,4]} #{value[7,4]} #{value[11,4]}"
  end

  def format_document(value)
    "#{value[0,3]}.#{value[3,3]}.#{value[6,3]}-#{value[9,3]}"
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Monuciper App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css',
                             media: 'all',
                             'data-turbolinks-track': 'reload',
                             integrity: 'sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor',
                             crossorigin: 'anonymous' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js',
                               'data-turbolinks-track': 'reload',
                               integrity: 'sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2',
                               crossorigin: 'anonymous' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js',
                               'data-turbolinks-track': 'reload',
                                integrity: 'sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=',
                                crossorigin: 'anonymous' %>
    <%= javascript_include_tag "application", media: "all"  %>
  
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Municipe</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Municipe", "/", class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <% if params[:controller] == "residents" %>class="active"<% end %>><a href="/">Residents</a></li>
           
          </ul>
        </div>
      </div>
    </nav>  
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/residents/_form.html.erb
<%= form_for(@resident, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @resident.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo:</h4>

      <ul>
      <% @resident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-6">
  <div class="form-group">
    <%= f.label :photo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :photo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :full_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :full_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :document, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :document, class: "form-control", data: { 'js' => 'cpf' } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :health_card_document, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :health_card_document, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control", data: { 'js' => 'phoneDDI' }  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birthdate, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :birthdate, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>&nbsp;
    <div class="col-sm-10">
      <%= f.select :status, ResidentEnum::Statuses.list.collect {|name| [ I18n.t("#{name}"), name ]},
                            { :selected => @resident.try(:status) },
                            class: 'form-control' %>
    </div>                        
  </div>

  <%= f.fields_for :addresses do |address_form| %>
    <%= address_form.hidden_field :id %>
    <div class="form-group">
        <%= address_form.label :zipcode, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= address_form.text_field :zipcode, class: 'form-control', 
                                     data: { 'js' => 'cep' } ,
                                     required: true %>
      </div>
    </div>    
    <div class="form-group">
      <%= address_form.label :street, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"> 
        <%= address_form.text_field :street, class: 'form-control', required: true %>
      </div>  
    </div>
    <div class="form-group">
      <%= address_form.label :neighboorhood, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"> 
        <%= address_form.text_field :neighboorhood, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= address_form.label :city, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"> 
        <%= address_form.text_field :city, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= address_form.label :state, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"> 
        <%= address_form.text_field :state, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="form-group">
      <%= address_form.label :ibge_code, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"> 
        <%= address_form.text_field :ibge_code, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= address_form.label :complement, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10"> 
        <%= address_form.text_field :complement, class: 'form-control' %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
</div>  
<% end %>

app/views/residents/_list.html.erb
<% @residents.each do |resident| %>
  <%= content_tag :tr, id: dom_id(resident), class: dom_class(resident) do %>
                <td><%= resident.full_name %></td>
                <td><%= format_document(resident.document) %></td>
                <td><%= format_brazilian_health_card_number(resident.health_card_document) %></td>
                <td><%= resident.email %></td>
                <td><%= resident.birthdate %></td>
                <td><%= resident.phone %></td>
                <td><%= resident.status %></td>
    <td><%= link_to 'Editar', edit_resident_path(resident) %></td>
  <% end %>
<% end %>

app/views/residents/edit.html.erb
<div class="page-header">
  <%= link_to residents_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @resident, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando Municipe</h1>
</div>

<%= render 'form' %>

app/views/residents/index.html.erb
<div class="page-header">
  <%= link_to new_resident_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Municipe
  <% end %>
  <h1>Listando Municipe</h1>
  <%= form_tag residents_path, :action => 'index', :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Pesquisar" %>
      </p>
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th> <%= Resident.human_attribute_name(:full_name) %> </th>
        <th> <%= Resident.human_attribute_name(:document) %> </th>
        <th> <%= Resident.human_attribute_name(:health_card_document) %> </th>
        <th> <%= Resident.human_attribute_name(:email) %> </th>
        <th> <%= Resident.human_attribute_name(:birthdate) %> </th>
        <th> <%= Resident.human_attribute_name(:phone) %> </th>
        <th> <%= Resident.human_attribute_name(:status) %> </th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: 'list' %>
    </tbody>
  </table>
</div>

app/views/residents/new.html.erb
<div class="page-header">
  <%= link_to residents_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo Municipe</h1>
</div>

<%= render 'form' %>